name: Build Plugin Pre-Release

on:
  release:
    types: [ prereleased, released ]

jobs:
  build:
    name: Build Plugin Artifact
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Generate plugin artifact
        run: |
          rsync -rc --exclude-from="$GITHUB_WORKSPACE/.distignore" "$GITHUB_WORKSPACE/" release/ --delete --delete-excluded
          cd "${GITHUB_WORKSPACE}/release" || exit
          zip -r "${GITHUB_WORKSPACE}/mailin-honeypot.zip" .

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{github.workspace}}/mailin-honeypot.zip
          asset_name: mailin-honeypot.zip
          asset_content_type: application/zip
